/*
 * This file is part of the Buildings and Habitats object Model (BHoM)
 * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
 *
 * Each contributor holds copyright over their respective contributions.
 * The project versioning (Git) records all such contribution source information.
 *                                           
 *                                                                              
 * The BHoM is free software: you can redistribute it and/or modify         
 * it under the terms of the GNU Lesser General Public License as published by  
 * the Free Software Foundation, either version 3.0 of the License, or          
 * (at your option) any later version.                                          
 *                                                                              
 * The BHoM is distributed in the hope that it will be useful,              
 * but WITHOUT ANY WARRANTY; without even the implied warranty of               
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 
 * GNU Lesser General Public License for more details.                          
 *                                                                            
 * You should have received a copy of the GNU Lesser General Public License     
 * along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.      
 */

using System.ComponentModel;

namespace BH.oM.EmbodiedSuffering.Elements
{
    [Description("A list of countries around the globe derived from: https://www.worldometers.info/geography/alphabetical-list-of-countries/")]
    public enum Country
    {
        Undefined,
        Afghanistan,
        Albania,
        Algeria,
        Andorra,
        Angola,
        Anguilla = 153,
        AntiguaAndBarbuda,
        Argentina,
        Armenia,
        Australia,
        Austria,
        Azerbaijan,
        Bahamas,
        Bahrain,
        Bangladesh,
        Barbados,
        Belarus,
        Belgium,
        Belize,
        Benin,
        Bermuda = 154,
        Bhutan,
        Bolivia,
        BosniaAndHerzegovina,
        Botswana,
        Brazil,
        BritishVirginIslands = 155,
        Brunei,
        Bulgaria,
        BurkinaFaso,
        Burundi,
        CoteDIvoire,
        CaboVerde,
        Cambodia,
        Cameroon,
        Canada,
        CaymanIslands = 156,
        CentralAfricanRepublic,
        Chad,
        Chile,
        China,
        ChristmasIsland = 157,
        CocosKeelingIsland = 158,
        Colombia,
        Comoros,
        Congo,
        CostaRica,
        Croatia,
        Cuba,
        Curacao = 159,
        Cyprus,
        CzechRepublic,
        DemocraticRepublicOfCongo,
        Denmark,
        Djibouti,
        Dominica,
        DominicanRepublic,
        Ecuador,
        Egypt,
        ElSalvador,
        EquatorialGuinea,
        Eritrea,
        Estonia,
        Eswatini,
        Ethiopia,
        Fiji,
        Finland,
        France,
        FrenchPolynesia = 160,
        Gabon,
        Gambia,
        Georgia,
        Germany,
        Ghana,
        Greece,
        Grenada,
        Guatemala,
        Guadeloupe = 161,
        Guinea,
        GuineaBissau,
        Guyana,
        Haiti,
        HeardAndMcDonaldIsland = 162,
        HolySee,
        Honduras,
        HongKong = 150,
        Hungary,
        Iceland,
        India,
        Indonesia,
        Iran,
        Iraq,
        Ireland,
        Israel,
        Italy,
        Jamaica,
        Japan,
        Jordan,
        Kazakhstan,
        Kenya,
        Kiribati,
        Kosovo = 151,
        Kuwait,
        Kyrgyzstan,
        Laos,
        Latvia,
        Lebanon,
        Lesotho,
        Liberia,
        Libya,
        Liechtenstein,
        Lithuania,
        Luxembourg,
        Macau = 163,
        Macedonia = 164,
        Madagascar,
        Malawi,
        Malaysia,
        Maldives,
        Mali,
        Malta,
        MarshallIslands,
        Mauritania,
        Mauritius,
        Mayotte = 165,
        Mexico,
        Micronesia,
        Moldova,
        Monaco,
        Mongolia,
        Montserrat = 166,
        Montenegro,
        Morocco,
        Mozambique,
        Myanmar,
        Namibia,
        Nauru,
        Nepal,
        Netherlands,
        NewCalendonia = 167,
        NewZealand,
        Nicaragua,
        Niger,
        Nigeria,
        Niue = 168,
        NorthKorea,
        NorthMacedonia,
        Norway,
        Oman,
        Pakistan,
        Palau,
        PalestineState,
        Panama,
        PapuaNewGuinea,
        Paraguay,
        Peru,
        Philippines,
        Poland,
        Portugal,
        Qatar,
        Reunion = 169,
        Romania,
        Russia,
        Rwanda,
        SaintKittsAndNevis,
        SaintLucia,
        SaintMaarten = 170,
        SaintVincentAndTheGrenadines,
        Samoa,
        SanMarino,
        SaoTomeAndPrincipe,
        SaudiArabia,
        Senegal,
        Serbia,
        Seychelles,
        SierraLeone,
        Singapore,
        Slovakia,
        Slovenia,
        SolomonIslands,
        Somalia,
        SouthAfrica,
        SouthKorea,
        SouthSudan,
        Spain,
        SriLanka,
        Sudan,
        Suriname,
        Sweden,
        Switzerland,
        Syria,
        Taiwan = 152,
        Tajikistan,
        Tanzania,
        Thailand,
        TimorLeste,
        Togo,
        Tonga,
        TrinidadAndTobago,
        Tunisia,
        Turkey,
        Turkmenistan,
        TurksAndCaicosIslands = 171,
        Tuvalu,
        Uganda,
        Ukraine,
        UnitedArabEmirates,
        UnitedKingdom,
        UnitedStatesOfAmerica,
        Uruguay,
        Uzbekistan,
        Vanuatu,
        VaticanCity = 172,
        Venezuela,
        Vietnam,
        Yemen,
        Zambia,
        Zimbabwe
    }
}